/**
 * Seeds the LOCAL wrangler-dev KV state (e2e/worker/.wrangler) before Playwright
 * starts the worker. Never touches a Cloudflare account (`--local` only).
 */
import { execFileSync } from 'node:child_process'
import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const e2eRoot = dirname(dirname(fileURLToPath(import.meta.url)))
const workerDir = join(e2eRoot, 'worker')
const wrangler = join(e2eRoot, 'node_modules', '.bin', 'wrangler')

// `.dev.vars` is gitignored repo-wide (real deployments put secrets there), so
// the e2e harness generates its throwaway local values instead of committing them.
writeFileSync(
  join(workerDir, '.dev.vars'),
  [
    '# Generated by e2e/scripts/seed-kv.mjs — local-only, never a real credential.',
    'CONSENT_TOKEN_SECRET=e2e-local-secret-32-characters!!',
    '# Explore round-trip: mock ClickHouse endpoint hosted by e2e/scripts/page-server.mjs.',
    'CLICKHOUSE_QUERY_URL=http://127.0.0.1:8788/e2e-clickhouse',
    ''
  ].join('\n')
)

const siteConfig = {
  siteId: 'site_e2e',
  domain: 'localhost',
  workerVersion: '0.0.0',
  shadowStart: '2026-01-01T00:00:00.000Z',
  enforcementStart: null,
  mode: 'SHADOW',
  consentConfigured: true,
  state1TokenTTL: 86400,
  ipHandling: 'hash_salt',
  // Page origin (8788) is cross-origin to the worker (8791): CORS allowlist entries.
  trustedDomains: ['localhost:8788', '127.0.0.1:8788'],
  driftDetection: { enabled: true, quarantineNew: false, alertThreshold: 0.05 }
}

function kvPut(key, value) {
  execFileSync(wrangler, ['kv', 'key', 'put', key, value, '--binding', 'ATTESTRACK_KV', '--local'], {
    cwd: workerDir,
    stdio: 'inherit',
    env: { ...process.env, WRANGLER_SEND_METRICS: 'false' }
  })
}

kvPut('attestrack:portal:site_config', JSON.stringify(siteConfig))
kvPut('attestrack:policy:privacy', 'E2E privacy policy document.\n')
kvPut('attestrack:policy:terms', 'E2E terms of use document.\n')
process.stderr.write('[seed-kv] local KV seeded for e2e\n')
