export interface WorkerTemplateOptions {
  siteId: string
  kvNamespaceBinding: string
}

export function buildWranglerToml(opts: WorkerTemplateOptions): string {
  return `# Generated by @attestrue/deploy
# Worker secrets (wrangler secret put <NAME>):
#   CONSENT_TOKEN_SECRET (required)
#   CLICKHOUSE_HTTP_URL, CLICKHOUSE_QUERY_URL, CLICKHOUSE_USER, CLICKHOUSE_PASSWORD
#   TINYBIRD_TOKEN, TINYBIRD_DATASOURCE, TINYBIRD_API_URL (optional)
#   GOOGLE_MP_API_SECRET, GOOGLE_MEASUREMENT_ID
#   META_ACCESS_TOKEN, META_PIXEL_ID
#   TIKTOK_ACCESS_TOKEN, TIKTOK_PIXEL_ID
#   MICROSOFT_UET_ACCESS_TOKEN, MICROSOFT_UET_TAG_ID
name = "attestrack-${opts.siteId.replace(/[^a-z0-9-]/gi, '-').toLowerCase()}"
main = "worker.ts"
compatibility_date = "2024-12-01"

[[kv_namespaces]]
binding = "ATTESTRACK_KV"
id = "${opts.kvNamespaceBinding}"

[vars]
SITE_ID = "${opts.siteId}"
`
}

export function buildWorkerEntry(): string {
  return `import { createCloudflareHostRuntime } from '@attestrue/host-cloudflare-worker'
import { createAttestrackFetchHandler, noopStrategyLoader } from '@attestrue/worker-core'
import { allBundledStrategies } from '@attestrue/strategies'

interface Env {
  ATTESTRACK_KV: KVNamespace
  CONSENT_TOKEN_SECRET: string
  SITE_ID: string
}

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const host = createCloudflareHostRuntime({
      bindings: { kv: env.ATTESTRACK_KV },
      executionCtx: ctx,
      secretValues: {
        CONSENT_TOKEN_SECRET: env.CONSENT_TOKEN_SECRET
      }
    })
    const handler = createAttestrackFetchHandler({
      host,
      consentSecretName: 'CONSENT_TOKEN_SECRET',
      bundledStrategies: allBundledStrategies('CONSENT_TOKEN_SECRET'),
      strategyLoader: noopStrategyLoader
    })
    return handler(request)
  }
}
`
}
